### ISSUE TITLE
add description when creating new period

### ISSUE THREAD

**Issue by julian-ao** [appKom/online-opptak#135]
it is not so easy to understand the difference between regular and optional committees

**Comment by fredrir** [comment]
> it is not so easy to understand the difference between regular and optional committees

Oja lol, info ikonet som forklarer er ikke synlig, men mulig å klikke 
![image](https://github.com/user-attachments/assets/0b6d7d5f-8f3a-4d25-8c70-7a4f9daaf9a3)

**Comment by julian-ao** [comment]
whaaat haha
