### ISSUE TITLE
Setup email sending out interviewtimes

### ISSUE THREAD

**Issue by fredrir** [appKom/online-opptak#148]
- Should include emails to committees with interview times for each applicant
- Should include an email to each applicant containing that applicants interview with each committee

**Comment by sindremil** [comment]
Er ideen at vi som admins skal utføre en handling for å sende mails, eller skal det skje automatisk når søkeperioden er over? @fredrir

**Comment by sindremil** [comment]
Typ trykke på en knapp i et dashbord

**Comment by fredrir** [comment]
> Typ trykke på en knapp i et dashbord

Hmm, burde egt skje automatisk. Tror issuet "Make matching algorithm run at end of application-period" skal prøve på det
