### ISSUE TITLE
Look into ways of sending SMS that interview times has been sent

### ISSUE THREAD

**Issue by fredrir** [appKom/online-opptak#197]

**Comment by fredrir** [comment]
Virker som det er mulig: https://github.com/projectashik/nextjs-twilio-send-message

**Comment by fredrir** [comment]
Vil koste rundt 70-80kr for å sende en SMS til hver søker info om intervjutider. Er dette @julian-ao noe vi tenker trenger?

Tror det kan være lurt, med tanke på hvordan e-postene havner i søppelpost, og at mellomrommet mellom vi sender ut mail om intervjutider og når folk har intervjuer vil være kort

**Comment by fredrir** [comment]
> Vil koste rundt 70-80kr for å sende en SMS til hver søker info om intervjutider. Er dette @julian-ao noe vi tenker trenger?
> 
> Tror det kan være lurt, med tanke på hvordan e-postene havner i søppelpost, og at mellomrommet mellom vi sender ut mail om intervjutider og når folk har intervjuer vil være kort

https://www.twilio.com/en-us/sms/pricing/no

**Comment by julian-ao** [comment]
det kan jo fort bli veldig dyrt... mine eposter havner ikke i søppelpost lenger. var det ikke bare på ntnu adresser dere andre ikke fikk epostene?

**Comment by julian-ao** [comment]
vent, du mente 80kr totalt? trodde det var per SMS...

**Comment by julian-ao** [comment]
Ser nå at dette er prisene per "segment". Hvis hver melding er over 160 tegn, blir den delt opp i segmenter med maks 160 tegn:
![image](https://github.com/user-attachments/assets/464e2cc0-b327-42d6-b430-658a8d8dbf92)

**Comment by fredrir** [comment]
> vent, du mente 80kr totalt? trodde det var per SMS...

Ahahh nei... det hadde blitt litt mye ja😅

**Comment by fredrir** [comment]
> Ser nå at dette er prisene per "segment". Hvis hver melding er over 160 tegn, blir den delt opp i segmenter med maks 160 tegn:
> 
> ![image](https://github.com/user-attachments/assets/464e2cc0-b327-42d6-b430-658a8d8dbf92)
> 
> 

Kan enten sende typ "Du har fått intervju, sjekk e-posten din for å se når, hilsen Appkom <3" eller sende intervjutidene på SMS, men da blir det fort over 160 tegn

**Comment by julian-ao** [comment]
Da blir det evt. dobbelt så dyrt ja, blir lettere for folk da...
