### ISSUE TITLE
Should we allow applicants to only apply for a optionalCommittee?

### ISSUE THREAD

**Issue by fredrir** [appKom/online-opptak#228]
Per nå, er det eksempelvis ikke mulig for en søke å kun søke "Feminit" som valgfri komite, utenom å velge minst en annen komite

**Comment by julian-ao** [comment]
Usikker på hva som burde være lov her, burde kanskje være lov å kun velge en valgfri komite ja?

**Comment by fredrir** [comment]
Enig! Er jo et edge case, men ser heller ikke noe i veien at man kun typ søker feminit og ikke noe annet
