### ISSUE TITLE
Fix responsiveness

### ISSUE THREAD

**Issue by fredrir** [appKom/online-opptak#339]
The logo is a bit too big in the navbar, and the buttons in homepage should be in a row 
![image](https://github.com/user-attachments/assets/bfde0366-e04a-4336-9d89-0f33773c008e)

**Comment by fredrir** [comment]
> Sikker på at det er plass til at knappene ligger ved siden av hverandre?

Kan sjekke, men hvis ikke så kan knappene f.eks ta opp full width? Ser litt rart ut nå

**Comment by julian-ao** [comment]
Ja, ser littrart ut. Tror faksitsk atde pleide å ta opp hele bredden, før vi fiksa Next 14. Sikkert noe av sylingen på `Link`-taggene som fucka seg opp.

**Comment by fredrir** [comment]
Tror det har noe med at man ikke kan/burde style Link attributtene direkte
